# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef53ce21cf6a5eb9921a17687be0b5d1af411f2014dfdf2e043aa0d24f09cd1f5e23a352d8d3d03eb130100460f7add2a2daa38500e0a9f625338ffc571f3e31

test:
  secret_key_base: 73afee3f55271f57c7be9e6b7f7d63f92bd95ec74b460ddcae8e8ca4addca672f1c43af8840b34e227f5d5aca81777a91f8d1aac51201927e18e7b56bb6b6193

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
